## Container engine (lxc or apptainer at the moment)
CONTAINER_ENGINE: "apptainer"
SINGULARITY_COMMAND_ALIAS: "apptainer" # singularity or apptainer (only relevant when using apptainer as container engine)

## Cgroups version: v1 (Lecacy or Hybrid mode) or v2 (Unified mode)
CGROUPS_VERSION: "v1"

## Orchestrator
ORCHESTRATOR_URL: "orchestrator"
ORCHESTRATOR_PORT: 5000

# CouchDB
COUCHDB_URL: "couchdb"
COUCHDB_PORT: 5984

# OpenTSDB:
OPENTSDB_URL: "opentsdb"
OPENTSDB_PORT: 4242
